

export const RoomsNames =[
    'Tavern',
'Landing',
'Food Storage',
'Ambush/Trap Corridor',
'Beloved Statue',
'Cursed Statue',
'Dead End',
'Executioner`s Block',
'Fountain',
'Harbor / Port',
'Haunted Corridor',
'Marketplace',
'Murder/Assassin’s Row / Dangerous AF place',
'Portal',
'Trash Pile',
'Watch Post',
'Scenic View',
'Fireworks storage',
'Hall of Wonders',
'Arena',
'Dwelling / Home',
'Holy Shrine',
'Smithy',
'Sorcerous Sundries',
'Bird Roost',
'Store/Ware-house',
'Holy Temple',
'Trading Post',
'Arms Shop',
'Arcane Retreat',
'Beast`s Lair',
'Dusty Cellar',
'Forgotten Cache',
'Flooded Chamber',
'Gladiator Pit',
'Minion Hideout',
'Neglected Shrine',
'Sacrificial Chamber',
'Evil Shrine',
'Smuggling Spot',
'Pest`s Nest',
'Vacated Shop',
'Abandoned Room',
'Ballroom',
'Bloody Room',
'Catacombs',
'Chapel',
'Charred Room',
'Chasm',
'Fuel Chute',
'Collapsed Room',
'Conservatory',
'Creaky Hallway / Noisy Room',
'Crypt',
'Dining Room',
'Furnace Room',
'Gallery',
'Game Room',
'Gardens',
'Graveyard',
'Gymnasium',
'Junk Room',
'Kitchen',
'Larder',
'Library',
'Bedroom',
'Mystic Elevator',
'Operating Laboratory',
'Music Room',
'Patio',
'Pentagram Chamber',
'Research Laboratory',
'Servants Quarters',
'Hidden Stairs',
'Statuary Corridor',
'Storeroom',
'High Outlook',
'Interior Lake',
'Vault',
'Wine Cellar',
'Arsenal',
'Bathroom',
'Cave',
'Drawing Room',
'Dungeon',
'Laundry',
'Locket Room',
'Menagerie',
'Nursery',
'Panic Room',
'Roof Landing / Highest Point',
'Rookery (Bird Nests)',
'Sewing Room',
'Solarium',
'Storm Cellar',
'Study',
'Theater',
'Tree House',
'Large Drop',
'Foundry',
'Forge',
'Bakery',
'Bath',
'Open Space',
'Conference Room',
'Cafeteria',
'Dispensery',
'Garbage Pickup',
'Sports Center',
'Mechanics',
'Assembly',
'Phone Room',
'Observatory',
'Office',
'Trophy Room',
'Art Studio',
'Treasury',
'Vault',
'Traps!',
'Mimic Room :^)',
'Private Study',
'Bar',
'Club',
'Lounge',
'Apothecary',
'Armorer',
'Blacksmith',
'Art Dealer',
'Asylum',
'Barber',
'Bookbinder',
'Bowyer / Carpentry',
'Brewery',
'Brothel',
'Butcher',
'Candlemaker',
'Cheesemaker',
'Clock room',
'Courthouse',
'Curios',
'Fortuneteller',
'Furrier / Pelter',
'Gambling Den',
'General Supply',
'Glassworks',
'Granary',
'Hatter',
'Jeweler',
'Waiting Room',
'Leather working',
'Livestock holding',
'Locksmith',
'Masonry',
'Mill',
'Money lender',
'Criminal Hangout',
'Orphanage',
'Mount tamer',
'Doctor / Clinic',
'Printer / Engraver',
'Private Room',
'Shoemaker / Cobbler',
'Stonecarver',
'Tailor / Cloth mill',
'Guest room',
'Taxidermist',
'Vet / Animal doctor',
'Watchtower',
'Weaver',
'Winery',
'Dragon`s Lair',
'Clan Lair',
'The lair of another villain',
'Endless horde of enemies',
'Stables',
'Guard`s Garrison',
'Prison Cells'
]

export class MagicItem{
    public Item:string; public ItemExplanation:string;
    public ItemAge:string; public ItemAgeExplanation:string;
    public Activation:string;
    public Powers:Array<string>;
    public Curses:Array<string>;

    constructor(
        Item:string = null, ItemExplanation:string =null,
        ItemAge:string = null, ItemAgeExplanation:string =null,
        Activation:string = null,
        Powers:Array<string> = [],
        Curses:Array<string> =[]
    ){
        this.Item = Item; this.ItemExplanation = ItemExplanation;
        this.ItemAge = ItemAge; this.ItemAgeExplanation = ItemAgeExplanation;
        this.Activation = Activation;
        this.Powers = Powers;
        this.Curses = Curses;
    }
}

export class Town{ //a random town with some generic information
    public Wealth:string;
    public TownSize:string; public TownSizeExplanation:string;
    public GovtType:string; public GovtTypeExplanation:string;
    public EconomicFocus:string; public EconomicFocusExplanation:string;
    public Biome:string; public BiomeExplanation:string;

    constructor(Wealth:string = null,
        TownSize:string = null, TownSizeExplanation:string = null,
        GovtType:string = null, GovtTypeExplanation:string = null,
        EconomicFocus:string = null, EconomicFocusExplanation:string = null,
        Biome:string = null, BiomeExplanation:string = null
        ){
            this.TownSize = TownSize; this.TownSizeExplanation = TownSizeExplanation;
            this.Wealth = Wealth;
            this.GovtType = GovtType; this.GovtTypeExplanation = GovtTypeExplanation;
            this.EconomicFocus = EconomicFocus; this.EconomicFocusExplanation = EconomicFocusExplanation;
            this.Biome = Biome; this.BiomeExplanation = BiomeExplanation;
        }
}

export class EndOfTheWorld{ //generic details about the end of the world in this setting
    public EndType:string; public EndTypeExplanation:string;
    public Timing:string; public TimingExplanation:string;

    constructor(EndType:string = null, EndTypeExplanation:string = null, Timing:string = null, TimingExplanation:string = null){
        this.EndType = EndType; this.EndTypeExplanation = EndTypeExplanation;
        this.Timing = Timing; this.TimingExplanation = TimingExplanation;
    }
}

export const ItemsNames =[
'Mace',
'Club',
'Halberd',
'Straight Sword',
'Dagger',
'Greatsword',
'Great Hammer',
'Hammer',
'Polearm',
'Axe',
'Scythe',
'Twin Blade',
'Great Axe',
'Whip',
'Giant Weapon',
'Curved Sword',
'Katana',
'Rapier',
'Piercing Sword',
'Flail',
'Lance',
'Spear',
'Claws',
'Fist Weapon',
'Knife',
'Cleaver',
'Pickaxe',
'Cane',
'Pike',
'Trident',
'Bident',
'Lucerne',
'Sickle',
'Staff',
'Shiv',

'Bow',
'Crossbow',
'Greatbow',
'Shortbow',
'Longbow',
'Repeater Crossbow',
'Shield Crossbow',
'Light Crossbow',
'Heavy Crossbow',
'Bowgun',
'Throwing Knives',
'Steel Balls',
'Explosives',
'Shuriken',
'Javelins',
'Sling',
'Blowgun',
'Boomerang',
'Chakram',
'Throwing Axe',
'Recurve Bow',
'Arrows',
'Bolts',
'Darts',
'Special Ammo',

'Gauntlets',
'Shield',
'Chestplate',
'Arm guards',
'Vambraces',
'Pauldrons',
'Greaves',
'Faulds',
'Knee pads',
'Helmet (open)',
'Breastplate',
'Hauberk',
'Elbow Pads',
'Heavy Jacket',
'Reinforced Clothing',
'Coif',
'Cuirass',
'Sabaton',
'Tasset',
'Helmet (closed)',
'Tower Shield',
'Buckler',

'Shirt',
'Pants',
'Shoes',
'Underwear',
'Boots',
'Ring',
'Hair clip/pin',
'Leg warmers',
'Leggings',
'Bracelet',
'Necklace',
'Belt',
'Earrings',
'Piercing',
'Socks',
'Sweater',
'Jacket',
'Scarf',
'Hat',
'Bandana',
'Wig',
'Thigh highs',
'arm wamers',
'gloves',
'shorts',
'glasses',
'monocle',
'mask',
'goggles',
'skirt',

'Shotgun',
'Rifle',
'Pistol',
'Blunderbuss',
'Sniper Rifle',
'Flare Gun',
'Musket',
'Sub Machine Gun',
'Bolt Action rifle',
'Lever action rifle',
'carbine',
'Combat shotgun',
'Semi auto shotgun',
'Automatic shotgun',
'Gatling gun',
'Machine pistol',
'light machine gun',
'heavy machine gun',
'machine gun',
'handgun',
'Revolver',
'Hand Cannon',
'Airsoft Gun',
'Paintball gun',
'potato cannon',
'cap gun',
'water gun',
'nerf gun',
'Speargun',
'BB gun',
'Energy weapon',
'RPG / Missile Launcher',
'Flame thrower',

'Trebuchet',
'Catapult',
'Drill/Ram',
'Cannon',
'Railgun',
'Artillery Cannon',
'Motor',
'Railgun',
'Missile Launcher',
'Giant Machine Gun',

'Book',
'Orb',
'Scroll',
'Phone',
'Computer',
'Doll',
'Picture',
'Power tool',
'Car',
'Wagon',
'Key',
'Weights',
'Fan',
'Wheel',
'yo-yo',
'Foam Weapon',
'Card board weapon',
'Cards',
'bed sheet',
'Speakers',
'TV',
'Cup',
'Handle',
'Pitcher',
'Paper weight',
'Cart',
'Painting',
'Statue',
'Rope',
'Wire',
'Currency',
'Disc',
'Potion',
'Lantern',
'Candle',
'Lamp',
'Lighter',
'Pipe',
'Flag / Banner',
'Horn',
'Trumpet',
'Piano',
'Flute',
'Harmonica',
'Whistle',
'Brush',
'Pen',
'Paper',
'Dice',
'Guitar',
'Harp',
'Bass',
'Triangle',
'Square',
'Cube',
'Pyramid',
'Headphones',
'Microphone',
'Paint brush',
'Paint',
'Liquid',
'Gas',
'Balloon',
'Container',
'Bag',
'Gum',
'Food item',
'Alcohol',
'A living creature',
'A corpse',
'Crutch',
'Chair',
'Table',
'Shelf',
'Rug',
'Bed',
'Mattress',
'Cushion',
'Pillow',
'Mirror',
'Plug',
'Hula Hoop',
'Rag',
'Machine',
'Artifial Intelligence',
'Drums',
'Drumsticks',
'Match',
'Badge',
'Plush Toy',
'Toy',
'Collar',
'Umbrella',
'Glider',
'Elixir',
'Draught',
'Vial',
'Philter',
'Tonic',
'Brew',
'Ichor',
'Juice',
'Concoction'
]

export const ItemsExplanations =[
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',
'Melee Weapon',

'Ranged Weapon',
'Ranged Weapon',
'Ranged Weapon',
'Ranged Weapon',
'Ranged Weapon',
'Ranged Weapon',
'Ranged Weapon',
'Ranged Weapon',
'Ranged Weapon',
'Ranged Weapon Gun',
'Ranged Weapon',
'Ranged Weapon',
'Ranged Weapon Explosive',
'Ranged Weapon',
'Ranged Weapon',
'Ranged Weapon',
'Ranged Weapon',
'Ranged Weapon',
'Ranged Weapon',
'Ranged Weapon',
'Ranged Weapon',
'Ranged Weapon',
'Ranged Weapon',
'Ranged Weapon',
'Ranged Weapon',

'Armor',
'Armor Shield',
'Armor',
'Armor',
'Armor',
'Armor',
'Armor',
'Armor',
'Armor',
'Armor',
'Armor',
'Armor',
'Armor',
'Armor',
'Armor',
'Armor',
'Armor',
'Armor',
'Armor',
'Armor',
'Armor Shield',
'Armor Shield',

'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',
'Clothing',

'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun Toy',
'Ranged Weapon Gun Toy',
'Ranged Weapon Gun Toy',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun',
'Ranged Weapon Gun Explosive',
'Ranged Weapon Gun',

'Siege Weapon',
'Siege Weapon',
'Siege Weapon',
'Siege Weapon Gun',
'Siege Weapon',
'Siege Weapon',
'Siege Weapon Gun Explosive',
'Siege Weapon',
'Siege Weapon Gun Explosive',
'Siege Weapon',

'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc Toy',
'Etc',
'Etc Toy',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc',
'Etc'
]

export const ItemAgeName=[
'Ancient',
'Old',
'Primordial',
'New',
'Fresh',
'What you would expect',
'A lifetime',
'Futuristic',
'Impossible',
'Young',
'Adult'
]

export const ItemAgeExplanation=[
    '',
    '',
    'The item is made of or connected to the very foundation of the world',
    '',
    '',
    'The age makes sense for the context the item is found and what the item actually is',
    '',
    '',
    'Something about the item`s age simply does not make sense',
    'Early portion of its life usage',
    'Has about half its life usage left'
    ]

export const ActivationName=[
'Default',
'Innate',
'Words',
'Sacrifice',
'"Use"',
'Always on',
'One time use',
'Randomly',
'When it feels like it',
'Thoughts',
'Gestures',
'Environmental Condition',
'Positivity',
'Negativity',
'When no one is touching it',
'When NOT in use',
'When no one is looking at it',
'When in its element',
'Good',
'Evil',
'Lawfulness',
'Chaos',
'For X goal'
]

export const Power=[
'Improve Damage',
'Improve Health',
'Improve Defenses',
'Reduce Damage',
'Reduce Health',
'Reduce Defenses',
'Always returns',
'Invoke fire',
'Invoke ice',
'invoke electricity',
'invoke darkness',
'invoke light',
'invoke nature',
'invoke life',
'invoke air',
'invoke earth',
'resist fire',
'resist ice',
'resist electricity',
'resist darkness',
'resist light',
'resist nature',
'resist life',
'resist air',
'resist earth',
'explode',
'implode',
'grows',
'shrinks',
'invisible',
'makes visible',
'incorporeal',
'anti-incorporeal',
'homing',
'healing',
'improve sense',
'reduce sense',
'improve intelligence',
'reduce intelligence',
'improve strength',
'reduce strength',
'improve agility',
'reduce agility',
'improve speed',
'reduce speed',
'improve charisma',
'reduce charisma',
'lucky',
'unlucky',
'vampiric',
'sharing',
'arcing',
'paired item',
'telepathic',
'empathic',
'mind numbing',
'wrathful',
'greedy',
'envious',
'lustful',
'prideful',
'lazy',
'sinful',
'temperence',
'just',
'paired self',
'exhausting',
'invigorating',
'stealing',
'joyous',
'faithful',
'loyal',
'patient',
'kind',
'humble',
'chaste',
'virtuous',
'good',
'evil',
'unholy',
'holy',
'divine',
'profane',
'slaying',
'Racist / Bane',
'Poisonous',
'Toxic',
'Resist poison',
'Resist Toxic',
'unclean',
'clean',
'Bleeding',
'Resist bleed',
'Shaping',
'Transforming',
'Other form',
'Great personality',
'Chatty',
'Smelly',
'Ascendant',
'Transcendent',
'Cybernetic',
'Biotic',
'Acidic',
'Basic (chemistry)',
'Piercing',
'Slashing',
'Bludgeoning',
'Ironic',
'Forceful',
'Pushing',
'Pulling',
'Rising',
'Falling',
'Gravity',
'Identifying',
'Mutating',
'Swimming',
'Climbing',
'Experience',
'Athletic',
'Acrobatic',
'Enslaving',
'Controlling',
'Intense',
'Accelerating',
'Decelerating',
'Mathematical',
'Curving',
'Straight',
'Pocket Dimension',
'Psychic',
'Wifi Enabled',
'Loud',
'Quiet',
'Hydrating',
'Drying',
'Swapping',
'eleporting',
'Distance',
'Long range',
'short range',
'Taunting',
'Intimidating',
'Scary',
'Spooky',
'Eerie',
'Terrifying',
'Gorey',
'Respectful',
'Dignified',
'Shining',
'Maddening',
'Sane',
'Non-reflective',
'Reflect',
'Smiling',
'Sad',
'Time warping',
'Pause',
'Space warping',
'Nuclear',
'Magnetic',
'Attractive',
'Beastial',
'Humane',
'Draconic',
'Demonic',
'Angelic',
'Chaotic',
'Lawful',
'Willful',
'Hyper',
'Earth shaker',
'Fiery',
'Heart',
'Ashbringer',
'Phoenix',
'Leviathan',
'Behemoth',
'Gojira',
'Destroying',
'Kong',
'Magical',
'Anti magic',
'Contrarian',
'Assimilating',
'Mimic',
'Changing',
'Spinning',
'Gyrating',
'Balanced',
'Unbalanced',
'More Ammo',
'Less Ammo',
'Spread',
'Pattern',
'Special Move',
'Area of Affect',
'Line',
'Cone',
'Hexagon',
'Pentagon',
'Square',
'Cube',
'Cylinder',
'Storming',
'Hurricane',
'Typhoon',
'Earthquake',
'Water spout',
'Volcanic',
'Meteor',
'Glorious',
'Beautiful',
'Ugly',
'Totally Normal',
'Deceptive',
'Ruling',
'Crystal',
'Intelligent',
'Musical',
'Sonic',
'Silencing',
'Reinforced',
'Durable',
'Bouncy',
'Static',
'Random',
'Happens often',
'Crit city',
'Anti Crit',
'Charging',
'Strange Physics',
'Jerk',
'Cannibal',
'Death',
'Pleasing',
'Healing',
'Vigor',
'Vitality',
'Might',
'Courage',
'Necro Resistance',
'Necrotic',
'Stoneskin',
'Barkskin',
'Charming',
'Shielding',
'Breathe Element',
'Growth',
'Shrink',
'Comprehend',
'Fertility',
'Luck',
'Mana',
'Arcane',
'Animalistic',
'Dreams',
'Nightmares',
'Stamina',
'Knowledge',
'Disguise',
'Full',
'Youth',
'Age',
'Aura',
'Farsight',
'Invulnerable',
'Skill',
'Midas (gold)',
'Hatred',
'Love',
'Future Sight',
'Leech',
'Traceless',
'Graceful',
'Lying',
'Unlucky',
'Possession',
'Wakefulness',
'Flying',
'Peace',
'Regenerate',
'Truth',
'Navigate',
'Sharing',
'Invisibility',
'Hide',
'Gender Change',
'Race Change',
'Divide',
'Multiply',
'Flavorful',
'Cleaning',
'Disease',
'Resist Disease',
'Rebirth',
'Elemental form',
'True form',
'Anti-depressant',
'New Form',
'Night vision',
'Panacea',
'Sleep',
'Hallucinating',
'Omen',
'Blur',
'Deaf',
'Mute',
'Dancing',
'Happiness',
'Asphyxiation',
'Petrify',
'Stunning',
'Immobilize',
'Fidgeting',
'Itchy',
'Attraction',
'Weakness',
'Anxious',
'Shame',
'Paranoia',
'Summons',
'Fear',
'Relaxing',
'Bad Trip',
'Dizzy',
'Finances',
'Spasms',
'Laughter',
'Addiction',
'Drunk',
'Pain',
'Pleasure'
]

export const ApocalypseNames =[
'The Sun Goes Out',
'The Sun Erupts',
'Meteoric Impact',
'Volcanic-Ice Age',
'Green House Runaway',
'Global Flood',
'War',
'Nuclear Contamination',
'Sudden Non-existence',
'Phase Shift',
'Everyone wakes up',
'Big Crunch',
'Roko`s Basilisk',
'Gates of Hell Open / Heaven Invades',
'The dead rise again',
'Heaven Invades',
'Almighty Space Flea',
'Microscopic Black Hole',
'Plague',
'Ecological Collapse (Famine)',
'Aliens',
'Madness',
'MADness',
'Big Bang',
'Heat Death',
'Causality breaks down',
'God rises',
'Gamma Ray Burst',
'Loss of atmosphere',
'Giant Storm',
'The earth shatters',
'Death',
'“Grey Goo”'
]

export const ApcalypseExplanations =[
    'The main source of heat, light, and/or energy in the world suddenly ceases to exist',
    'A massive explosion or burst of radioactivity affects existence, heat and light may no longer exist either after this event',
    'A massive explosion or impact occurs on the world, the debris sent upward or sheer force from this impact may cause dramatic changes in the climate',
    'A volcanic eruption destroys a large local area, but the deposit of ash enters the atmosphere and causes severe climate changes to create a new Ice Age',
    'A positive feedback loop occurs causing the planet to heat up infinitely, you can also choose a different "end" where a different chemical/physical process begins an infinite loop causing the world to be inhospitable',
    'The water level rises suddenly and to a large degree, the world "map" and climate changes drastically as tidal waves and endless rains change the landscape',
    'A war threatens the world to such a degree as to wipe out all life if it does not cease',
    'A strange substance is released into the world somehow and it is inherently harmful to all life',
    'The world and/or the people in it, simply, end.',
    'Reality begins to unravel as a new "reality" or set of physics begins to take over the current one. This new "reality" is inherently harmful to the lives in the current one. For an example, imagine if suddenly half the world froze at 100 Celsius but the other half remained normal.',
    'The old reality was a dream, or something untrue. Whatever the case, everyone almost simultaneously finds themselves in a new reality which they must navigate well or perish',
    'The world collapses in on itself until it becomes a singular infinitely dense point in which nothing can survive',
    'An artificial intelligence is created, but it was too advanced/intelligent for the purpose it was made for. In seeking to fulfill its purpose it became too powerful, and is causing severe harm to people or the world in general. An example would be a "happiness machine" that tries to kidnap people and keep them drugged to maximize endorphine "happiness", or it tries to destroy the world so that there is no "un-happiness" to be perceived',
    'Another reality is opened into the current one, and its denizens are inherently harmful to the current life of the world. They are likely attempting genocide or conquest',
    'A simple way would be "zombie apocalypse" where dead corpses want to destroy all sapient life. The more complex route would be that death no longer applies, but the world cannot sustain an infinitely increasing population, leading to vicious conflict for remaining resources',
    'An alien/foreign almighty being becomes known or present in the world. Whatever its desires, it does not consider the natives and likely causes unprecedented harm as it changes the world to suit its needs',
    'The world is slowly being torn apart by rifts in space-time, they are hardly noticeable at first, but will become more violent as time passes.',
    'A disease or virus quickly spreads through life in the world, and it is highly hostile to such life.',
    'For whatever reason, the current environment is no longer able to sustain life for most if not all of its inhabitants. Many other apcalypse types naturally lead to this.',
    'A foreign/alien race finds the world/area and seeks to conquer it to suit their needs, regardless of what it means for the natives',
    'A majority of the populace simply goes insane, the world suffers as important jobs are no longer being performed or are performed with intent to harm.',
    'World leaders are ready to cause inrreparable damage to the world in response to perceived aggression on a national level, even though if every faction committed to this act it would destroy the world totally',
    'Reality itself explodes and a new one is made',
    'Reality stretches out infinitely, particles will no longer be able to interact with each other due to the distance. There is no more heat or energy, and any remaining matter is surrounded by void',
    'Time or "cause and effect" no longer "works". Past people or events will occur in the modern day, or people find themselves in other points of time at random. The world cannot function well in this temporal chaos.',
    'An impossibly powerful being makes itself known to the world or becomes active again. The desires and actions of this being may not be benign to the currently existing life.',
    'The world suddenly experiences a great wave of radiation and energy, possibly vaporizing or poisoning much of the world in an instant. Most often caused by a "nearby" star turning into a black hole, an explosion so powerful that it implodes as well from gravitational energy.',
    'The air is no longer being held by the world and matter easily floats off into the void of space. A world without breathable air is obviously not very hospitable to life.',
    'A hurricane or typhoon forms, one so large and powerful that it lifts the sturdiest foundations, tears the environment apart, and floods most of the world.',
    'Possibly a massive earthquake, the ground shakes with tremendous force and deep rifts open in the earth. Most structures are destroyed, lives are lost, and other disasters may occur such as tsunamis or volcanic eruptions',
    'Everything simply, dies. The sudden loss of life and the functions certain people or life forms once performed make survival even more difficult for the survivors.',
    'A material or robotic/hive intelligence spreads through the world, turning all matter into more of itself.'
]

export const TimingOfApocalypseNames =[
'Post Apocalypse',
'Golden Age, no end in sight (apoc is unexpected and sudden to masses)',
'Middle of Apocalypse, society exists but is collapsing',
'Beginning of Apocalypse, decline begins',
'New Era (world remembers previous apoc)'
]

export const TimingOfApocalypseExplanations =[
    'It has already happened, but the fate of survivors is uncertain',
    'An apocalypse is unexpected and sudden to masses, it may not be considered or known at all',
    'Society exists but it is quickly collapsing as all resources are being brought to deal with the existential threat',
    'The decline of society begins, resources and lives are rapidly being lost. Life may be "normal" in much of the world, but it is obvious that will change soon.',
    'The world remembers the previous "apocalypse" and has finally stabilized since then. The aforementioned apocalypse that was randomly generated is a story of that last age, or may be yet the next challenge.'
]

export const WealthOfTownNames =[
'Decrepit',
'Poor',
'Median Income',
'Wealthy',
'Economic Miracle'
]

export const TownSizeNames =[
    'Thorp / Tiny',
    'Village / Small',
    'Town / Average',
    'City / Large',
    'Rural / Sparse',
    'Metropolis / Largest'    
]

export const TownSizeExplanations =[
    'There is enough people that generally knows each other or even intimately knows everyone in the area',
    'Everyone is generally able to know each other, but there are distinct families or factions. It may be impossible to truly know every soul in the village',
    'Most people are familiar with each other, but a governing force is necessary to keep the peace between many strangers at this stage',
    'There is a large number of people gathered in this given area, the majority of which relate to each other through a government or faction which is charged with peace keeping. Most people are present here likely due to a valuable resource or environmental quirk',
    'While the area may be physically large, there are few people who live here. They may have very close bonds, are isolated hermits, or only vaguely know each other. Generally each person is expected to be self-sufficient',
    'A city of the largest caliber, with enough souls and resources to challenge other nations alone if need be. This city is likely generations old but still holds highly valuable resources'
]
